name: weather_forecast_app
description: A stunning Apple Weather-style app with intelligent multi-API forecast merging
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # HTTP & Networking  
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Storage & Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.1.0

  # UI & Animations
  cupertino_icons: ^1.0.6
  lottie: ^2.7.0
  rive: ^0.12.4
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0

  # Maps & Weather Visualization
  flutter_map: ^6.1.0
  latlong2: ^0.8.1
  
  # Utilities
  intl: ^0.19.0
  timeago: ^3.6.0
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

  # Firebase (Optional - for analytics)
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4

  # Background Tasks
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Testing
  mockito: ^5.4.4
  faker: ^2.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/lottie/
    - assets/rive/
    - assets/icons/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700

    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProText-Semibold.ttf
          weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#2196F3"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#2196F3"